spring.application.name=CryptoPulse

server.port=5455

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/cryptopulse
spring.datasource.username=cryptouser
spring.datasource.password=Sandybvl@1254
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

