name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up JDK for building the Spring Boot app
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the Spring Boot app with Maven
    - name: Build JAR with Maven
      run: mvn clean package

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 5: Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

    # Step 6: Push the Docker image to Docker Hub
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
