name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build Spring Boot JAR file
    - name: Build JAR file
      run: mvn clean package -DskipTests

    # Step 4: Find the JAR file name dynamically
    - name: Find JAR file
      id: find-jar
      run: echo "JAR_FILE=$(find target -name '*.jar' | head -n 1)" >> $GITHUB_ENV

    # Step 5: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build Docker image
    - name: Build Docker image
      run: |
        docker build --build-arg JAR_FILE=${{ env.JAR_FILE }} -t your-dockerhub-username/springboot-app:${{ github.sha }} .

    # Step 7: Push Docker image to DockerHub
    - name: Push Docker image
      run: |
        docker push your-dockerhub-username/springboot-app:${{ github.sha }}
